baseURL = "https://mreeve-snl.github.io/wiki-test/"
languageCode = 'en-us'

title = "Wiki Test"
publishDir = "public"

canonifyURLs = true

###############################################################################
# Docsy
###############################################################################
enableGitInfo = true

# disable taxonomies
disableKinds = ["taxonomy"]
# deprecated directories
ignoreFiles = []

# Override module mounts, mainly so that we can update fontawesome.
# NOTE: this is based on docsy's config.yaml from v0.6.0, and must be updated if the docsy theme ever is.
#       https://github.com/google/docsy/blob/v0.6.0/config.yaml#L24-L38
[module]

	proxy = "direct"

	[[module.imports]]
	path = "github.com/google/docsy"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/bootstrap"
    target = "assets/vendor/bootstrap"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free"
    target = "assets/vendor/Font-Awesome"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "Docs"
    weight = -102
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/docs/"
  [[menu.main]]
    name = "Events"
    weight = -101
    pre = "<i class='fas fa-calendar pr-2'></i>"
    url = "/events/"
  [[menu.main]]
    name = "Blog"
    weight = -100
    pre = "<i class='fas fa-rss pr-2'></i>"
    url = "BLOG GOES HERE"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/cisagov/LME"

###############################################################################
# Docsy - Output Formats
###############################################################################
[outputs]
section = [ "HTML" ]

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    # For MathJax
    # https://gohugo.io/content-management/mathematics/#setup
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.highlight]
          style = "monokai"
###############################################################################
# Docsy - DrawIO configuration
###############################################################################
[params.drawio]
enable = true

###############################################################################
# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

###############################################################################
# Docsy - Language configuration
###############################################################################
[languages]
  [languages.en]
    title = "wiki-test"
    languageName ="English"
    weight = 1

###############################################################################
# Docsy - Site Parameters
###############################################################################
[params]
  github_repo = "https://github.com/mreeve-snl/wiki-test"
  github_project_repo = "https://github.com/cisagov/lme"

  #copyright = "LME"
  #privacy_policy = "PRIVACY POLICY"
  #trademark = "CISA TM HERE"

  # Text label for the version menu in the top bar of the website.
  version_menu = "Version"

  # The major.minor version tag for the version of the docs represented in this
  # branch of the repository. Used in the "version-banner" partial to display a
  # version number for this doc set.
  version = "main"

  # Flag used in the "version-banner" partial to decide whether to display a
  # banner on every page indicating that this is an archived version of the docs.
  archived_version = false

  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = "https://mreeve-snl.github.io/wiki-test/"

  # A variable used in various docs to determine URLs for config files etc.
  # To find occurrences, search the repo for 'params "githubbranch"'.
  github_branch = "main"

  # Disable MathJax by default
  # NOTE: enable it per-page with `mathjax: true` in front matter
  mathjax = false

  # Disable Swagger UI by default
  # NOTE: enable it per-page with `swaggerui: true` in front matter
  swaggerui = false

  # Enable Lunr.js offline search
  offlineSearch = true
  offlineSearchSummaryLength = 200
  offlineSearchMaxResults = 25

  # Social media accounts
  [params.social]

    # Twitter account (used to set `twitter:site` in the SEO partial)
    twitter = "cisagov?"

  # These entries appear in the drop-down menu at the top of the website.
  [[params.versions]]
    version = "main"
    githubbranch = "main"
    url = "https://github.com/mreeve-snl/wiki-test/tree/main"
	#TODO: add this in
  [[params.versions]]
    version = "v1.0"
    githubbranch = "v1.0"
    url = "https://github.com/mreeve-snl/wiki-test/tree/main"

  # User interface configuration
  [params.ui]
	showLightDarkModeMenu = true
    # Enable the logo
    navbar_logo = true
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Enable the search box in the side bar.
    sidebar_search_disable = false
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Show expand/collapse icon for sidebar sections
    sidebar_menu_foldable = true
    # Disable about button in footer
    footer_about_enable = false

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      #[params.ui.feedback]
      #  enable = true
      #  # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
      #  # NOTE: the actual content of the responses is set in the "layouts/partials/feedback.html" file.
      #  yes = ""
      #  no = ""

  # Links in footer
  [params.links]
    [[params.links.user]]
      name = "X"
      icon = "fa-brands fa-x-twitter"
      desc = "Follow us on X to get the latest news!"
    [[params.links.user]]
      name = "YouTube"
      icon = "fab fa-youtube"
      desc = "Subscribe to our YouTube channel for the latest videos!"
    [[params.links.user]]
      name = "LinkedIn"
      icon = "fab fa-linkedin"
      desc = "Connect with us on LinkedIn for updates and networking!"
    [[params.links.user]]
      name = "Slack"
      icon = "fab fa-slack"
      desc = "Join the  Slack Workspace!"

